apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-health-k8s
  labels:
    app: go-health-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-health-k8s
  template:
    metadata:
      labels:
        app: go-health-k8s
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: go-health-k8s
          image: go-health-k8s:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: go-health-k8s-config
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
